<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>StmInstaller</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>0.1.2.4</Version>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="pack.zip" Condition="Exists('pack.zip')" />
    <Resource Include="app.ico" />
    <Resource Include="icon.png" />
  </ItemGroup>
</Project>
